'''

SED Machine flat field class
(c) 2015 Nick Konidaris

This class is an abstract wrapper around a flat-field correciton

'''
from numpy.polynomial.chebyshev import chebfit, chebval
import numpy as np


class FlatCorrection(object):
    '''SED machine flat field correction

    Generally there are several thousand such Extractions that are held for
    a single 2k x 2k frame. 

    Args:
        seg_id (int): Number from 1 to the maximum segment number. The segment
            number is generated by sextractor.
        correction (object): Some type of correction object.
        get_correction(lam): Returns the correction value for a given wavelength. Current default is no wavelength dependence.

    Examples:

    '''

    seg_id = None 
    correction = None

    def __init__(self, seg_id=None, correction=None):
        self.seg_id = seg_id
        self.correction = correction

    def get_correction(self, lam):
        ''' Returns correction spectrum, a number that averages about 1 for the frame.

        Args:
            lam: Wavelength in nm
        '''

        if self.correction is None:
            return 1.0
        else:
            return self.correction


